using UnityEngine;
using UnityEngine.InputSystem;

public static class KeyCodeConversionExtensions
{
	public static Key ToKey(this KeyCode o)
	{
		return o switch
		{
			KeyCode.None => (Key)0, 
			KeyCode.Backspace => (Key)65, 
			KeyCode.Delete => (Key)71, 
			KeyCode.Tab => (Key)3, 
			KeyCode.Clear => (Key)0, 
			KeyCode.Return => (Key)2, 
			KeyCode.Pause => (Key)76, 
			KeyCode.Escape => (Key)60, 
			KeyCode.Space => (Key)1, 
			KeyCode.Keypad0 => (Key)84, 
			KeyCode.Keypad1 => (Key)85, 
			KeyCode.Keypad2 => (Key)86, 
			KeyCode.Keypad3 => (Key)87, 
			KeyCode.Keypad4 => (Key)88, 
			KeyCode.Keypad5 => (Key)89, 
			KeyCode.Keypad6 => (Key)90, 
			KeyCode.Keypad7 => (Key)91, 
			KeyCode.Keypad8 => (Key)92, 
			KeyCode.Keypad9 => (Key)93, 
			KeyCode.KeypadPeriod => (Key)82, 
			KeyCode.KeypadDivide => (Key)78, 
			KeyCode.KeypadMultiply => (Key)79, 
			KeyCode.KeypadMinus => (Key)81, 
			KeyCode.KeypadPlus => (Key)80, 
			KeyCode.KeypadEnter => (Key)77, 
			KeyCode.KeypadEquals => (Key)83, 
			KeyCode.UpArrow => (Key)63, 
			KeyCode.DownArrow => (Key)64, 
			KeyCode.RightArrow => (Key)62, 
			KeyCode.LeftArrow => (Key)61, 
			KeyCode.Insert => (Key)70, 
			KeyCode.Home => (Key)68, 
			KeyCode.End => (Key)69, 
			KeyCode.PageUp => (Key)67, 
			KeyCode.PageDown => (Key)66, 
			KeyCode.F1 => (Key)94, 
			KeyCode.F2 => (Key)95, 
			KeyCode.F3 => (Key)96, 
			KeyCode.F4 => (Key)97, 
			KeyCode.F5 => (Key)98, 
			KeyCode.F6 => (Key)99, 
			KeyCode.F7 => (Key)100, 
			KeyCode.F8 => (Key)101, 
			KeyCode.F9 => (Key)102, 
			KeyCode.F10 => (Key)103, 
			KeyCode.F11 => (Key)104, 
			KeyCode.F12 => (Key)105, 
			KeyCode.F13 => (Key)112, 
			KeyCode.F14 => (Key)113, 
			KeyCode.F15 => (Key)114, 
			KeyCode.Alpha0 => (Key)50, 
			KeyCode.Alpha1 => (Key)41, 
			KeyCode.Alpha2 => (Key)42, 
			KeyCode.Alpha3 => (Key)43, 
			KeyCode.Alpha4 => (Key)44, 
			KeyCode.Alpha5 => (Key)45, 
			KeyCode.Alpha6 => (Key)46, 
			KeyCode.Alpha7 => (Key)47, 
			KeyCode.Alpha8 => (Key)48, 
			KeyCode.Alpha9 => (Key)49, 
			KeyCode.Quote => (Key)5, 
			KeyCode.Comma => (Key)7, 
			KeyCode.Minus => (Key)13, 
			KeyCode.Period => (Key)8, 
			KeyCode.Slash => (Key)9, 
			KeyCode.Semicolon => (Key)6, 
			KeyCode.Equals => (Key)14, 
			KeyCode.LeftBracket => (Key)11, 
			KeyCode.Backslash => (Key)10, 
			KeyCode.RightBracket => (Key)12, 
			KeyCode.BackQuote => (Key)4, 
			KeyCode.A => (Key)15, 
			KeyCode.B => (Key)16, 
			KeyCode.C => (Key)17, 
			KeyCode.D => (Key)18, 
			KeyCode.E => (Key)19, 
			KeyCode.F => (Key)20, 
			KeyCode.G => (Key)21, 
			KeyCode.H => (Key)22, 
			KeyCode.I => (Key)23, 
			KeyCode.J => (Key)24, 
			KeyCode.K => (Key)25, 
			KeyCode.L => (Key)26, 
			KeyCode.M => (Key)27, 
			KeyCode.N => (Key)28, 
			KeyCode.O => (Key)29, 
			KeyCode.P => (Key)30, 
			KeyCode.Q => (Key)31, 
			KeyCode.R => (Key)32, 
			KeyCode.S => (Key)33, 
			KeyCode.T => (Key)34, 
			KeyCode.U => (Key)35, 
			KeyCode.V => (Key)36, 
			KeyCode.W => (Key)37, 
			KeyCode.X => (Key)38, 
			KeyCode.Y => (Key)39, 
			KeyCode.Z => (Key)40, 
			KeyCode.Numlock => (Key)73, 
			KeyCode.CapsLock => (Key)72, 
			KeyCode.ScrollLock => (Key)75, 
			KeyCode.RightShift => (Key)52, 
			KeyCode.LeftShift => (Key)51, 
			KeyCode.RightControl => (Key)56, 
			KeyCode.LeftControl => (Key)55, 
			KeyCode.RightAlt => (Key)54, 
			KeyCode.LeftAlt => (Key)53, 
			KeyCode.LeftMeta => (Key)57, 
			KeyCode.LeftWindows => (Key)57, 
			KeyCode.RightMeta => (Key)58, 
			KeyCode.RightWindows => (Key)58, 
			KeyCode.AltGr => (Key)54, 
			KeyCode.Help => (Key)0, 
			KeyCode.Print => (Key)74, 
			KeyCode.SysReq => (Key)0, 
			KeyCode.Break => (Key)76, 
			KeyCode.Menu => (Key)59, 
			_ => (Key)0, 
		};
	}

	public static MouseButton ToMouseButton(this KeyCode o)
	{
		return o switch
		{
			KeyCode.Mouse0 => MouseButton.Left, 
			KeyCode.Mouse1 => MouseButton.Right, 
			KeyCode.Mouse2 => MouseButton.Middle, 
			KeyCode.Mouse3 => MouseButton.Back, 
			KeyCode.Mouse4 => MouseButton.Forward, 
			KeyCode.WheelUp => MouseButton.ScrollUp, 
			KeyCode.WheelDown => MouseButton.ScrollDown, 
			_ => MouseButton.None, 
		};
	}

	public static KeyCode ToKeyCode(this Key o)
	{
		//IL_0000: Unknown result type (might be due to invalid IL or missing references)
		//IL_01ae: Expected I4, but got Unknown
		return (int)o switch
		{
			0 => KeyCode.None, 
			1 => KeyCode.Space, 
			2 => KeyCode.Return, 
			3 => KeyCode.Tab, 
			4 => KeyCode.BackQuote, 
			5 => KeyCode.Quote, 
			6 => KeyCode.Semicolon, 
			7 => KeyCode.Comma, 
			8 => KeyCode.Period, 
			9 => KeyCode.Slash, 
			10 => KeyCode.Backslash, 
			11 => KeyCode.LeftBracket, 
			12 => KeyCode.RightBracket, 
			13 => KeyCode.Minus, 
			14 => KeyCode.Equals, 
			15 => KeyCode.A, 
			16 => KeyCode.B, 
			17 => KeyCode.C, 
			18 => KeyCode.D, 
			19 => KeyCode.E, 
			20 => KeyCode.F, 
			21 => KeyCode.G, 
			22 => KeyCode.H, 
			23 => KeyCode.I, 
			24 => KeyCode.J, 
			25 => KeyCode.K, 
			26 => KeyCode.L, 
			27 => KeyCode.M, 
			28 => KeyCode.N, 
			29 => KeyCode.O, 
			30 => KeyCode.P, 
			31 => KeyCode.Q, 
			32 => KeyCode.R, 
			33 => KeyCode.S, 
			34 => KeyCode.T, 
			35 => KeyCode.U, 
			36 => KeyCode.V, 
			37 => KeyCode.W, 
			38 => KeyCode.X, 
			39 => KeyCode.Y, 
			40 => KeyCode.Z, 
			41 => KeyCode.Alpha1, 
			42 => KeyCode.Alpha2, 
			43 => KeyCode.Alpha3, 
			44 => KeyCode.Alpha4, 
			45 => KeyCode.Alpha5, 
			46 => KeyCode.Alpha6, 
			47 => KeyCode.Alpha7, 
			48 => KeyCode.Alpha8, 
			49 => KeyCode.Alpha9, 
			50 => KeyCode.Alpha0, 
			51 => KeyCode.LeftShift, 
			52 => KeyCode.RightShift, 
			53 => KeyCode.LeftAlt, 
			54 => KeyCode.RightAlt, 
			55 => KeyCode.LeftControl, 
			56 => KeyCode.RightControl, 
			57 => KeyCode.LeftMeta, 
			58 => KeyCode.RightMeta, 
			59 => KeyCode.Menu, 
			60 => KeyCode.Escape, 
			61 => KeyCode.LeftArrow, 
			62 => KeyCode.RightArrow, 
			63 => KeyCode.UpArrow, 
			64 => KeyCode.DownArrow, 
			65 => KeyCode.Backspace, 
			66 => KeyCode.PageDown, 
			67 => KeyCode.PageUp, 
			68 => KeyCode.Home, 
			69 => KeyCode.End, 
			70 => KeyCode.Insert, 
			71 => KeyCode.Delete, 
			72 => KeyCode.CapsLock, 
			73 => KeyCode.Numlock, 
			74 => KeyCode.Print, 
			75 => KeyCode.ScrollLock, 
			76 => KeyCode.Pause, 
			77 => KeyCode.KeypadEnter, 
			78 => KeyCode.KeypadDivide, 
			79 => KeyCode.KeypadMultiply, 
			80 => KeyCode.KeypadPlus, 
			81 => KeyCode.KeypadMinus, 
			82 => KeyCode.KeypadPeriod, 
			83 => KeyCode.KeypadEquals, 
			84 => KeyCode.Keypad0, 
			85 => KeyCode.Keypad1, 
			86 => KeyCode.Keypad2, 
			87 => KeyCode.Keypad3, 
			88 => KeyCode.Keypad4, 
			89 => KeyCode.Keypad5, 
			90 => KeyCode.Keypad6, 
			91 => KeyCode.Keypad7, 
			92 => KeyCode.Keypad8, 
			93 => KeyCode.Keypad9, 
			94 => KeyCode.F1, 
			95 => KeyCode.F2, 
			96 => KeyCode.F3, 
			97 => KeyCode.F4, 
			98 => KeyCode.F5, 
			99 => KeyCode.F6, 
			100 => KeyCode.F7, 
			101 => KeyCode.F8, 
			102 => KeyCode.F9, 
			103 => KeyCode.F10, 
			104 => KeyCode.F11, 
			105 => KeyCode.F12, 
			_ => KeyCode.None, 
		};
	}

	public static KeyCode ToKeyCode(this MouseButton o)
	{
		return o switch
		{
			MouseButton.Left => KeyCode.Mouse0, 
			MouseButton.Right => KeyCode.Mouse1, 
			MouseButton.Middle => KeyCode.Mouse2, 
			MouseButton.Back => KeyCode.Mouse3, 
			MouseButton.Forward => KeyCode.Mouse4, 
			MouseButton.ScrollUp => KeyCode.WheelUp, 
			MouseButton.ScrollDown => KeyCode.WheelDown, 
			_ => KeyCode.None, 
		};
	}
}
